language: python
before_install:
- pip install pycodestyle
- pip install pytest
- pip install pytest-cov
- pip install coveralls
- pip install sphinx
- pip install sphinx_rtd_theme
install:
- pip install -r requirements.txt
- python setup.py install
script:
- find . -name \*.py -exec pycodestyle --max-line-length=120 --ignore=E402 {} +
- pytest --cov=artellapipe
- sphinx-apidoc -f -e -o docs/sphinx artellapipe
- sphinx-build -M html ./docs/sphinx ./
after_success:
- coveralls
- cd html && touch .nojekyll && cd ../
deploy:
  - provider: pages
    skip_cleanup: true
    github_token: "$GITHUB_TOKEN"
    keep_history: true
    local_dir: html
    on:
      branch: master
  - provider: pypi
    skip_cleanup: true
    user: tpoveda
    password:
      secure: CJGqSx45ucxZ2FEIP+T2LViqrZp7nBgbqXO6hFlCQWqVJCXNPPTyxcKjdNPz08kS8yGUgV9ShYPEsPyDPBVzEwo+q/vsD1+7grNUEHHxMBg/645SbNy7Zg1ilLJE7nmFB3r5fC0tqcyEiQ0HfEx4hL/XFuYFvyNHbAnRVX9QvvtQugGJ2sZi8YShGAu78dL9GcUIQ7ZpS/F4H28gxcqmP7pLd+OASgyH04qr2mWLSAhWai1d4/4tKDIThZAQPOUeUlN1XwpR6Yi64HxPhaMjWCBbM3nCf0o1RbBUDBQrZ/x2Lx/nYKR8IVhJZPnF4oQSFc24Mx23eShat4CMp9oFT6YyUDLmhl/plbQqlGz4Z9+a/WKNTPZBY02SQ8Q6AFcEHrwKInHnJztE55LZtgu/3cvBYkj59IVv8iysgbHEIV1q2BsnSeQj+VJ26qPC7vdJk7Ud5cu4VS8BRlmVr/2SgglFYhsDVzzZObriUYn9YHbH4zoGh2TuHczYUlflMUDxz9+7PQibBpvAkGHQGzo2r+DHeSzkw75rdWoaphJdfNmuqccFW7drQA06fYLTN3T1nR7a1wfBdWkWdPCYul2suLS0Gv/S9Zid2ywJO/iKqcmzOKrb0XUeXdFsU1m3udEeeJv2OaNO19RXGumRLKa0nOwbb8eBw5Y+wuzuJ5GsGnM=
    on:
      branch: master
      tags: true